# Generated by Django 5.2 on 2025-04-15 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('cualquier_momento', 'Cualquier momento'), ('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('repeticion_por_semana', models.IntegerField(default=0)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.estilo')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.frecuencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.tipohabito')),
            ],
        ),
        migrations.CreateModel(
            name='DiaHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.dia')),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habito')),
            ],
        ),
    ]
