# Generated by Django 5.2 on 2025-04-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habito_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dia',
            name='tipo',
            field=models.CharField(choices=[('semana', 'Día de la Semana'), ('fecha', 'Fecha Específica')], default='semana', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
